server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # HTTP: funciona con cámara nativa del celular (sin certificado)
  location /api/ {
    proxy_pass http://api:4000/api/;
    proxy_http_version 1.1;
    client_max_body_size 12m;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /uploads/ {
    proxy_pass http://api:4000/uploads/;
    proxy_set_header Host $host;
  }

  location /health {
    proxy_pass http://api:4000/health;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}

server {
  listen 443 ssl;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  ssl_certificate     /etc/nginx/certs/selfsigned.crt;
  ssl_certificate_key /etc/nginx/certs/selfsigned.key;
  ssl_protocols       TLSv1.2 TLSv1.3;

  # HTTPS: habilita cámara en vivo del navegador
  location /api/ {
    proxy_pass http://api:4000/api/;
    proxy_http_version 1.1;
    client_max_body_size 12m;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto https;
  }

  location /uploads/ {
    proxy_pass http://api:4000/uploads/;
    proxy_set_header Host $host;
  }

  location /health {
    proxy_pass http://api:4000/health;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
